### ISSUE TITLE
Floor Gallery Images Very Small

### ISSUE THREAD

**Issue by jsimonson2013** [rfugs21/classroomFinderIssues#12]
**Severity** 
_Trivial_ 

**Test Setup** 
Running the application on the emulator with Android X86 using Android Studio on Windows 10. 

**Details** 
After clicking the "Select Building" spinner, then selecting "East Towne Mall", an image of the East Towne Mall floor plan is displayed in the view. This image is very small and one might not be able to tell that this is an image of the floor plan. Clicking the image opens a full-screen view, which is clearly a floor plan of East Towne Mall. 

**Suggestion** 
Change the cell size of the GridView to accommodate larger images of floor plans.

**Comment by zkocken** [comment]
Thanks for the report. View scaling was implemented the day after this test repo was created.
