### ISSUE TITLE
No option to delete favorites

### ISSUE THREAD

**Issue by thuibr** [rfugs21/classroomFinderIssues#13]
**Severity**
_Trivial_

**Test Setup**
* Click on the Room Finder tab
* Select East Town Mall as Building
* Select Name of the Game as Current Location
* Select Spencer's as Destination
* Click Find
* Click and hold the middle of the screen
* Click the back button
* Click on the favorites tab

**Details**
There is no option to delete a favorite.

**Details**
There is not an option to delete favorites after adding them. This quickly fills up the favorites menu if you have a lot of favorites.

**Comment by rfugs21** [comment]
Favorites are able to be deleted as outlined in the README for this repo. Simply swipe left and the delete should occur. Confirmed to be working as intended. Thanks!
