### ISSUE TITLE
Headings on Home Screen are Centered, Selections are Left-Aligned.

### ISSUE THREAD

**Issue by jsimonson2013** [rfugs21/classroomFinderIssues#15]
**Severity**
_Trivial_

**Test Setup**
Running the application on the emulator with Android_Accelerated_x86 using Android Studio on Windows 10.

**Description**
On the home screen, after selecting from any of the spinners, selections are displayed. The resulting view elements are some text views of headings centered horizontally and some text views of selections left-aligned horizontally. This creates an inconsistent view.

**Suggestion**
Left-aligning the headings and spinners horizontally would avoid having to deal with centering spinner text views and still result in a consistent view.

**Comment by zkocken** [comment]
Thanks for the report. View scaling was implemented the day after this test repo was created.
