### ISSUE TITLE
Setting Sears to Destination Causes Crash

### ISSUE THREAD

**Issue by crosholt** [rfugs21/classroomFinderIssues#3]
**Severity**
_Blocker_

**Test Setup**
Running the application on a laptop (Mac OS or Windows) using the specified emulator.

**Details**
Setting the destination to Sears and setting the starting location to Name of the Game or other locations near Name of the Game, then pressing the Find button causes the application to crash.  Note that the reverse path does not cause the application to crash (meaning the starting location is Sears and the destination is any other location).

**Suggestion**
Check that Sears is a valid location in all parts of the code.

**Comment by rfugs21** [comment]
Error cause discovered; Neighbors of Sears did not contain Sears as one of their neighbors. Need to modify XML and push commit, but that should resolve this bug. Thanks!
