### ISSUE TITLE
Possible to Have Duplicate Favorites

### ISSUE THREAD

**Issue by crosholt** [rfugs21/classroomFinderIssues#4]
**Severity**
_Trivial_

**Test Setup**
Running the application on an Android phone (version 7.1.2).

**Details**
Can add the same path as a favorite more than once.

**Suggestion**
Check that any ordered pair (<start>, <destination>) being added as a favorite is not already a favorite.

**Comment by shreyashstha** [comment]
Thank you for reporting this issue. I took your suggestion and added a check for the same favorite.
