### ISSUE TITLE
Map is tiny thumbnail in "Floor Gallery"

### ISSUE THREAD

**Issue by thuibr** [rfugs21/classroomFinderIssues#8]
**Severity**
_critical_

**Test Setup**
* Select East Town Mall as Building

**Details**
The thumbnail for East Town Mall is tiny and hardly recognizable.

![screenshot from 2017-04-25 16 56 07](https://cloud.githubusercontent.com/assets/10468883/25409591/27af34b4-29d8-11e7-8d27-5a7dde9cf356.png)

**Comment by zkocken** [comment]
Thanks for the report. View scaling was implemented the day after this test repo was created.
