### ISSUE TITLE
No Location Carry-Over from Room Finder to Bathroom Finder

### ISSUE THREAD

**Issue by crosholt** [rfugs21/classroomFinderIssues#9]
**Severity**
_Trivial_

**Test Setup**
Running the application on an Android phone (version 7.1.2). 

**Details**
When switching from Room Finder to Bathroom Finder or vice versa, current location and destination do not carry over between the two tabs.

**Suggestion**
Have persistent starting locations and destinations available to both views.

**Comment by rfugs21** [comment]
Thanks for the suggestion, but this is not a feature we plan on implementing in this iteration of the project. Fields should not carry over between views.
